import {
  API_PATHS,
  getJson,
  postJson,
  type ApiResult,
  type CardsResult,
  type ConfigsResult,
  type LoginResult,
  type ProfileUpdate,
  type RegisterResult,
  type StatsResult,
  type UsersResult,
  type Terminal,
  type TerminalsResult,
  type GameEvent,
  type GameCharge,
  type EventsResult,
  type ChargesResult,
} from '@/types'

export const api = {
  getStats: () => getJson<StatsResult>(API_PATHS.stats),
  updateProfile: (profile: ProfileUpdate) => postJson<ApiResult>(API_PATHS.updateProfile, profile),
  login: (email: string, password: string) => postJson<LoginResult>(API_PATHS.login, { email, password }),
  currentUser: () => getJson<LoginResult>(API_PATHS.me),
  register: (email: string, password: string, username: string) =>
    postJson<RegisterResult>(API_PATHS.register, { email, password, username }),
  verifyEmail: (email: string, token: string) => postJson<ApiResult>(API_PATHS.verify, { email, token }),
  logout: () => postJson<ApiResult>('/api/auth/logout', {}),
  getCards: () => getJson<CardsResult>(API_PATHS.cards),
  bindCard: (email: string, accessCode: string, cardName: string, gameUserId?: number) =>
    postJson<ApiResult>(API_PATHS.bindCard, { email, accessCode, cardName, gameUserId }),
  getUsers: () => getJson<UsersResult>(API_PATHS.users),
  getTerminals: () => getJson<TerminalsResult>(API_PATHS.terminals),
  createTerminal: (terminal: Pick<Terminal, "keychipId" | "name" | "gameId" | "gameVersion">) => postJson<ApiResult>(API_PATHS.createTerminal, terminal),
  updateTerminal: (terminal: Terminal) => postJson<ApiResult>(API_PATHS.updateTerminal, terminal),
  deleteTerminal: (id: number) => postJson<ApiResult>(API_PATHS.deleteTerminal, { id }),
  getUserTerminals: () => getJson<TerminalsResult>(API_PATHS.userTerminals),
  createUserTerminal: (terminal: Pick<Terminal, 'keychipId' | 'name' | 'gameId' | 'gameVersion'>) => postJson<ApiResult>(API_PATHS.createUserTerminal, terminal),
  updateUserTerminal: (terminal: Terminal) => postJson<ApiResult>(API_PATHS.updateUserTerminal, terminal),
  deleteUserTerminal: (id: number) => postJson<ApiResult>(API_PATHS.deleteUserTerminal, { id }),
  getGameEvents: () => getJson<EventsResult>(API_PATHS.events),
  createGameEvent: (event: Omit<GameEvent, 'ID'>) => postJson<ApiResult>(API_PATHS.createEvent, event),
  updateGameEvent: (event: GameEvent) => postJson<ApiResult>(API_PATHS.updateEvent, event),
  deleteGameEvent: (id: number) => postJson<ApiResult>(API_PATHS.deleteEvent, { id }),
  getGameCharges: () => getJson<ChargesResult>(API_PATHS.charges),
  createGameCharge: (charge: GameCharge) => postJson<ApiResult>(API_PATHS.createCharge, charge),
  updateGameCharge: (charge: GameCharge) => postJson<ApiResult>(API_PATHS.updateCharge, charge),
  deleteGameCharge: (chargeId: number) => postJson<ApiResult>(API_PATHS.deleteCharge, { chargeId }),
  getConfigs: () => getJson<ConfigsResult>(API_PATHS.configs),
  updateConfig: (key: string, value: string) => postJson<ApiResult>(API_PATHS.updateConfig, { key, value }),
}

export default api
